# Week 3 - Intro to Data Analysis


## Import, cleaning, and filtering
### Using loops, functions, and conditionals

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

In [3]:
# Find week_3 when running from the repo, sessions, week_3, or scripts
CWD = Path.cwd()

CWD
print(CWD.parent)

ROOT = CWD.parent


DATA = ROOT / "data"
DATA
RAW = DATA / "raw"
RAW
# CLEAN = DATA / "clean"
# OUTPUT = ROOT / "output"

# print("Input:", RAW / "disney" / "disney_plus_shows.csv")
# print("Clean data:", CLEAN / "disney")
# print("Output:", OUTPUT)

/Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3

PosixPath('/Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/raw')

## Import and investigate

In [4]:
# Import a single dataset
df_raw = pd.read_csv(RAW / "disney" / "disney_plus_shows.csv")
df = df_raw.copy(deep=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      894 non-null    object
 1   title        894 non-null    object
 2   plot         866 non-null    object
 3   type         894 non-null    object
 4   rated        742 non-null    object
 5   year         894 non-null    object
 6   released_at  874 non-null    object
 7   added_at     992 non-null    object
 8   runtime      838 non-null    object
 9   genre        885 non-null    object
 10  director     689 non-null    object
 11  writer       743 non-null    object
 12  actors       870 non-null    object
 13  language     856 non-null    object
 14  country      869 non-null    object
 15  awards       556 non-null    object
 16  metascore    292 non-null    float64
 17  imdb_rating  879 non-null    float64
 18  imdb_votes   879 non-null    object
dtypes: float64(2), object(17)
memory usage: 147.4+ KB

In [7]:
print("df shape")
print(df.shape)

df shape
(992, 19)

In [8]:
# Basic investigation df.head(), df.info(), df.describe(), df.shape, df.nrows
print("df describe")
print(df.describe())
print("\n")

# df.columns
cols_all = df.columns
print(cols_all)

df describe
        metascore  imdb_rating
count  292.000000   879.000000
mean    62.061644     6.656428
std     15.776455     1.020352
min     19.000000     1.500000
25%     51.000000     6.100000
50%     61.000000     6.700000
75%     73.000000     7.400000
max     99.000000     9.700000


Index(['imdb_id', 'title', 'plot', 'type', 'rated', 'year', 'released_at',
       'added_at', 'runtime', 'genre', 'director', 'writer', 'actors',
       'language', 'country', 'awards', 'metascore', 'imdb_rating',
       'imdb_votes'],
      dtype='object')

# Crash course of pd.Series() and pd.DataFrame()

* API reference: https://pandas.pydata.org/docs/reference/index.html
* Official User Guide: https://pandas.pydata.org/docs/user_guide/index.html
* For a quick start: https://pandas.pydata.org/docs/user_guide/10min.html
* Community tutorials: https://pandas.pydata.org/docs/getting_started/tutorials.html
* Comparison with other tools: https://pandas.pydata.org/docs/getting_started/comparison/index.html

In [ ]:
# type(df)
type(df["actors"])
# type(df.actors)

# type(df[["actors", "year"]])
# type(df[["actors"]])

pandas.core.frame.DataFrame

In [22]:
titles = df["title"]
type(titles)

print(titles)

0                      10 Things I Hate About You
1                            101 Dalmatian Street
2                                  101 Dalmatians
3      101 Dalmatians 2: Patch's London Adventure
4                                  102 Dalmatians
                          ...
987                                        Zapped
988               Zenon: Girl of the 21st Century
989                             Zenon: The Zequel
990                                     Zenon: Z3
991                                      Zootopia
Name: title, Length: 992, dtype: object

In [26]:
df_main = df[["actors", "year"]]
type(df_main)

df_main.head()

                                              actors   year
0  Heath Ledger, Julia Stiles, Joseph Gordon-Levi...   1999
1  Josh Brener, Michaela Dietz, Bert Davis, Abiga...  2018–
2  Glenn Close, Jeff Daniels, Joely Richardson, J...   1996
3  Barry Bostwick, Jason Alexander, Martin Short,...   2002
4  Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...   2000

In [27]:
# Series and DataFrames have their own set of methods and attributes
# Review documentation
# print(titles.shape) # attribute of Series
# print(df.shape) # attribute of DataFrame

print(titles.dtype)

# print(df.dtype) # error because df doesn't have dtype
print(df.dtypes) # but it has df.dtypes

object
imdb_id         object
title           object
plot            object
type            object
rated           object
year            object
released_at     object
added_at        object
runtime         object
genre           object
director        object
writer          object
actors          object
language        object
country         object
awards          object
metascore      float64
imdb_rating    float64
imdb_votes      object
dtype: object

In [28]:
# Similarly with methods, some might seem identical, but they are not
# print(type(titles))
# print(titles.sort_values(ascending=False))

df.sort_values(by=["year", "title"]) # error because requires
# titles.sort_values(ascending=False)
# print(titles)

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
726,tt0019422,Steamboat Willie,"Mickey Mouse, piloting a steamboat, delights h...",movie,TV-Y7,1928,01 Jan 1929,"November 12, 2019",8 min,"Animation, Short, Comedy, Family, Musical","Ub Iwerks, Walt Disney",NaN,Walt Disney,English,USA,1 win.,NaN,7.6,"6,678"
42,tt0022647,Babes in the Woods,Two Dutch children stumble on a clearing in th...,movie,Approved,1932,19 Nov 1932,"November 12, 2019",8 min,"Family, Animation, Short, Comedy",Burt Gillett,NaN,"Pinto Colvig, Lucille La Verne",English,USA,NaN,NaN,6.8,799
279,tt0022899,Flowers and Trees,"An evil tree stump, jealous of two trees in lo...",movie,APPROVED,1932,30 Jul 1932,"November 12, 2019",8 min,"Animation, Short, Comedy",Burt Gillett,NaN,"Esther Campbell, Marion Darlington",English,USA,NaN,NaN,7.5,"1,547"
668,tt0023422,Santa's Workshop,Santa's little helpers must hurry to finish th...,movie,NaN,1932,10 Dec 1932,"November 12, 2019",7 min,"Animation, Family, Short",Wilfred Jackson,NaN,"Pinto Colvig, Walt Disney, Allan Watson",English,USA,NaN,NaN,7.4,"1,320"
848,tt0024451,The Pied Piper,"A piper saves a town from rat infestation, but...",movie,NaN,1933,16 Sep 1933,"November 12, 2019",8 min,"Animation, Short, Family, Fantasy, Musical",Wilfred Jackson,NaN,NaN,English,USA,1 win.,NaN,6.7,659
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"January 24, 2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"March 27, 2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"January 15, 2020",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"November 12, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"November 12, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# some methods return a new object, some modify in place - often can choose with argument inplace=True/False 
titles.sort_values(ascending=False)

titles_alphabetical_desc = titles.sort_values(ascending=False)
# print(titles_alphabetical_desc)
# print(titles)


titles_new = titles.copy()
titles_new.sort_values(ascending=False, inplace=True)
print(titles_new)

# titles_sorted = titles.sort_values(inplace=True) # this gives error
# print(titles_sorted)
# print(titles_sorted)

991                           Zootopia
990                          Zenon: Z3
989                  Zenon: The Zequel
988    Zenon: Girl of the 21st Century
987                             Zapped
                    ...
957                                NaN
964                                NaN
965                                NaN
966                                NaN
980                                NaN
Name: title, Length: 992, dtype: object

# Modifying, creating, and removing columns

In [31]:
# df["year_clean"]
df.columns

Index(['imdb_id', 'title', 'plot', 'type', 'rated', 'year', 'released_at',
       'added_at', 'runtime', 'genre', 'director', 'writer', 'actors',
       'language', 'country', 'awards', 'metascore', 'imdb_rating',
       'imdb_votes'],
      dtype='object')

In [12]:
# creating a new column (copy of an existing column)
df["year_clean"] = df["year"]

# print(type(df["year_clean"]))
# years = df["year"]
# print(type(years))
# print(years)

# creating a new column
df["metascore_pct"] = df["metascore"] / 100
df["imdb_pct"] = df["imdb_rating"] / 10

df.head()

# this creates empty values if either one is missing
df["avg_score"] = (df["metascore_pct"] + df["imdb_pct"]) / 2
df["avg_score_clean"] = df[["metascore_pct", "imdb_pct"]].mean(axis=1, skipna=True)  # skipna=True by default

# this allows to ignore nas
# df.head()

In [13]:
# creating two new columns
df[["year_clean", "release_date_clean"]] = df[["year", "released_at"]]
# df[["years_clean", "release_date_clean"]] = df[["released_at"]] # ValueError
# df[["years_clean", "release_date_clean"]] = df[["year_new", "released_at"]] # KeyError (not in index)

In [14]:
# renaming columns
df_temp = df.rename(columns={
    "avg_score": "avg_score_imdb_meta",
    "metascore_pct": "meta_drop",
    "imdb_pct":  "imdb_drop"
})

df_temp.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,awards,metascore,imdb_rating,imdb_votes,year_clean,meta_drop,imdb_drop,avg_score_imdb_meta,avg_score_clean,release_date_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,2 wins & 13 nominations.,70.0,7.3,"283,945",1999,0.70,0.73,0.715,0.715,31 Mar 1999
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,NaN,NaN,6.2,124,2018–,NaN,0.62,NaN,0.620,25 Mar 2019
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",1996,0.49,0.57,0.530,0.530,27 Nov 1996
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,5 wins & 10 nominations.,NaN,5.8,"7,434",2002,NaN,0.58,NaN,0.580,21 Jan 2003
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",2000,0.35,0.49,0.420,0.420,22 Nov 2000

In [15]:
# dropping columns
df_temp = df_temp.drop(columns=["year_clean", "meta_drop", "imdb_drop"])
df = df_temp.copy()

df.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,actors,language,country,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,"Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,"Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,"Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,"Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",0.420,0.420,22 Nov 2000

In [16]:
# Rename all raw columns to have _raw suffic
cols_raw = df_raw.columns
print(cols_raw)

cols_raw_mod = cols_raw + "_raw"
# or with list comprehension if more complicated
cols_raw_clean = [col.upper() + "_raw" for col in cols_raw]
print(cols_raw_clean)

cols_raw_clean = [col.lower() for col in cols_raw_clean]
print(cols_raw_clean)

Index(['imdb_id', 'title', 'plot', 'type', 'rated', 'year', 'released_at',
       'added_at', 'runtime', 'genre', 'director', 'writer', 'actors',
       'language', 'country', 'awards', 'metascore', 'imdb_rating',
       'imdb_votes'],
      dtype='object')
['IMDB_ID_raw', 'TITLE_raw', 'PLOT_raw', 'TYPE_raw', 'RATED_raw', 'YEAR_raw', 'RELEASED_AT_raw', 'ADDED_AT_raw', 'RUNTIME_raw', 'GENRE_raw', 'DIRECTOR_raw', 'WRITER_raw', 'ACTORS_raw', 'LANGUAGE_raw', 'COUNTRY_raw', 'AWARDS_raw', 'METASCORE_raw', 'IMDB_RATING_raw', 'IMDB_VOTES_raw']
['imdb_id_raw', 'title_raw', 'plot_raw', 'type_raw', 'rated_raw', 'year_raw', 'released_at_raw', 'added_at_raw', 'runtime_raw', 'genre_raw', 'director_raw', 'writer_raw', 'actors_raw', 'language_raw', 'country_raw', 'awards_raw', 'metascore_raw', 'imdb_rating_raw', 'imdb_votes_raw']

In [17]:
# assign all columns to a new dataset
df_temp = df_raw.copy(deep=True)
df_temp.columns = cols_raw_clean

df_temp.head()

# more complicated, rename the raw columns in our working dataframe

print(df_raw.columns)
print(df.columns)

# zip two lists - also very helpful in loops
# cols_zipped = zip(df_raw.columns, cols_raw_clean)
# for i in cols_zipped:
#     print(i)

# for old, new in cols_zipped:
#     print(old)
#     print(new)

# cols_to_rename = dict(zip(df_raw.columns, cols_raw_clean))

# df = df.rename(cols_to_rename)

# df.head()

Index(['imdb_id', 'title', 'plot', 'type', 'rated', 'year', 'released_at',
       'added_at', 'runtime', 'genre', 'director', 'writer', 'actors',
       'language', 'country', 'awards', 'metascore', 'imdb_rating',
       'imdb_votes'],
      dtype='object')
Index(['imdb_id', 'title', 'plot', 'type', 'rated', 'year', 'released_at',
       'added_at', 'runtime', 'genre', 'director', 'writer', 'actors',
       'language', 'country', 'awards', 'metascore', 'imdb_rating',
       'imdb_votes', 'avg_score_imdb_meta', 'avg_score_clean',
       'release_date_clean'],
      dtype='object')

## Converting variable types 

* Series.astype() -> special cases
* pd.to_numeric(); pd.to_datetime(); pd.to_string() -> (errors="raise" !!)

In [18]:
# Convert variable types

# intuition similar as with base pythion
df["avg_score_char"] = df["avg_score_imdb_meta"].astype(str)

# df["year_int"] = df["year"].astype(int)

df.head()

# MUCH BETTER

# df["year_int"] = pd.to_numeric(df["year"], errors="raise")
df["year_clean"] = pd.to_numeric(df["year"].str[0:4], errors="raise").fillna(9999).astype(int)

df.head()


# df["year_clean_check"] = pd.to_numeric(df["year"], errors="coerce")


# df["released_date_clean"] = pd.to_datetime(df["released_date"], errors="raise")

# df["released_date_clean"].head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,country,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,USA,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,"UK, USA, Canada",NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,"USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,USA,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",0.420,0.420,22 Nov 2000,0.42000000000000004,2000

## Indexing
### df.loc[] -> location based indexing -> ALWAYS use
### df.iloc[] -> integer position based indexing -> NEVER use

In [19]:
print(df.index)
print(titles.index)
# print(df[0:3])

RangeIndex(start=0, stop=992, step=1)
RangeIndex(start=0, stop=992, step=1)

In [20]:
titles[0:4]

0                    10 Things I Hate About You
1                          101 Dalmatian Street
2                                101 Dalmatians
3    101 Dalmatians 2: Patch's London Adventure
Name: title, dtype: object

In [21]:
df[0:4]

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,country,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,USA,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,"UK, USA, Canada",NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,"USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,USA,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002

In [22]:
## .loc
df.loc[[0, 1, 2, 3, 7]]

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,country,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,USA,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,"UK, USA, Canada",NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,"USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,USA,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002
7,tt0120623,A Bug's Life,"A misfit ant, looking for ""warriors"" to save h...",movie,G,1998,25 Nov 1998,"November 12, 2019",95 min,"Animation, Adventure, Comedy, Family",...,USA,Nominated for 1 Oscar. Another 14 wins & 20 no...,77.0,7.2,"257,065",0.745,0.745,25 Nov 1998,0.745,1998

In [23]:
my_filter = df["year_clean"] >= 2015

# print(type(my_filter[0]))

# df_new_movies = df.loc[my_filter]

df_new_movies = df.loc[df["year_clean"]>= 2015]
df_new_movies

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,country,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,"UK, USA, Canada",NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018
8,tt12076020,A Celebration of the Music from Coco,NaN,movie,NaN,2020,10 Apr 2020,"April 10, 2020",NaN,Music,...,USA,NaN,NaN,7.6,35,NaN,0.760,10 Apr 2020,nan,2020
14,tt1620680,A Wrinkle in Time,After the disappearance of her scientist fathe...,movie,PG,2018,09 Mar 2018,"March 25, 2020",109 min,"Adventure, Family, Fantasy, Sci-Fi",...,USA,5 wins & 15 nominations.,53.0,4.2,"38,659",0.475,0.475,09 Mar 2018,0.47500000000000003,2018
15,tt6139732,Aladdin,A kind-hearted street urchin and a power-hungr...,movie,PG,2019,24 May 2019,"January 8, 2020",128 min,"Adventure, Family, Fantasy, Musical, Romance",...,USA,7 wins & 32 nominations.,53.0,7.0,"204,537",0.615,0.615,24 May 2019,0.615,2019
27,tt4622802,America's National Parks,Series exploring the incredible wildlife of Am...,series,TV-G,2015–,06 Dec 2015,"January 15, 2020",NaN,Documentary,...,USA,NaN,NaN,7.9,73,NaN,0.790,06 Dec 2015,nan,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977,tt6959706,BarkFest,Nat Geo WILD celebrates pawsome dogs with its ...,series,NaN,2017–,NaN,"November 12, 2019",35 min,NaN,...,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,2017
980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"November 12, 2019",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,9999
981,tt6945708,Year Million,An in depth look into what our future will loo...,series,NaN,2017,15 May 2017,"January 1, 2020",NaN,"Documentary, Drama, Sci-Fi",...,USA,NaN,NaN,7.5,324,NaN,0.750,15 May 2017,nan,2017
986,tt6878820,Z-O-M-B-I-E-S,Students from Zombietown are transferred to a ...,movie,TV-G,2018,16 Feb 2018,"November 12, 2019",94 min,"Family, Musical, Romance",...,USA,1 nomination.,NaN,6.3,"2,993",NaN,0.630,16 Feb 2018,nan,2018
991,tt2948356,Zootopia,"In a city of anthropomorphic animals, a rookie...",movie,PG,2016,04 Mar 2016,"November 12, 2019",108 min,"Animation, Adventure, Comedy, Crime, Family, M...",...,USA,Won 1 Oscar. Another 46 wins & 71 nominations.,78.0,8.0,"410,437",0.790,0.790,04 Mar 2016,0.79,2016

In [24]:
# df_ok_movies = df.loc[ 6<= df["imdb_rating"] <= 8]
df_ok_movies = df.loc[(df["imdb_rating"] >= 6) & (df["imdb_rating"] <= 8)]

df_ok_movies = df.loc[df["imdb_rating"].between(6, 8, inclusive="both")]

df_ok_movies.head()

df_ok_movies = df_ok_movies[df_ok_movies["rated"].isin(["PG-13", "PG", "Approved"])]

df_ok_movies.head()

pg_condition = df["rated"].str.contains("PG", na=False)

df_ok_movies= df_ok_movies.loc[pg_condition]

df_ok_movies.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,country,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,USA,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999
5,tt1846442,12 Dates of Christmas,"A story that follows Kate, a young woman who a...",movie,PG,2011,11 Dec 2011,"November 12, 2019",90 min,"Comedy, Fantasy, Romance",...,USA,1 nomination.,NaN,6.3,"4,933",NaN,0.630,11 Dec 2011,nan,2011
15,tt6139732,Aladdin,A kind-hearted street urchin and a power-hungr...,movie,PG,2019,24 May 2019,"January 8, 2020",128 min,"Adventure, Family, Fantasy, Musical, Romance",...,USA,7 wins & 32 nominations.,53.0,7.0,"204,537",0.615,0.615,24 May 2019,0.615,2019
20,tt1014759,Alice in Wonderland,Nineteen-year-old Alice returns to the magical...,movie,PG,2010,05 Mar 2010,"November 12, 2019",108 min,"Adventure, Family, Fantasy",...,USA,Won 2 Oscars. Another 33 wins & 63 nominations.,53.0,6.4,"371,772",0.585,0.585,05 Mar 2010,0.585,2010
37,tt0230011,Atlantis: The Lost Empire,A young adventurer named Milo Thatch joins an ...,movie,PG,2001,22 Jun 2001,"November 12, 2019",95 min,"Animation, Action, Adventure, Family, Fantasy,...",...,USA,2 wins & 14 nominations.,52.0,6.9,"98,258",0.605,0.605,22 Jun 2001,0.605,2001

In [25]:
# Overwriting values
df["rated_clean"] = df["rated"]
my_filter = df["rated_clean"].isna()

print(my_filter)

df.loc[my_filter, "rated_clean"] = "missing"

df

df_temp = df.copy()

df_temp.loc[my_filter, "rated"] = "missing"

df_temp

0      False
1       True
2      False
3      False
4      False
       ...
987    False
988    False
989    False
990    False
991    False
Name: rated_clean, Length: 992, dtype: bool

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean,rated_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999,PG-13
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,missing,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018,missing
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996,G
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002,G
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",0.420,0.420,22 Nov 2000,0.42000000000000004,2000,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,tt3544734,Zapped,"When Zoey's mom remarries, Zoey finds it hard ...",movie,TV-G,2014,23 Jun 2014,"November 12, 2019",102 min,"Comedy, Family, Fantasy",...,5 wins & 1 nomination.,NaN,5.1,"3,750",NaN,0.510,23 Jun 2014,nan,2014,TV-G
988,tt0186726,Zenon: Girl of the 21st Century,An inquisitive teenager pries into suspected d...,movie,TV-G,1999,23 Jan 1999,"November 12, 2019",97 min,"Adventure, Comedy, Family, Sci-Fi",...,2 nominations.,NaN,6.4,"6,378",NaN,0.640,23 Jan 1999,nan,1999,TV-G
989,tt0271271,Zenon: The Zequel,A mischievous fifteen-year-old girl living on ...,movie,TV-G,2001,12 Jan 2001,"November 12, 2019",100 min,"Comedy, Family, Adventure, Sci-Fi",...,1 nomination.,NaN,5.9,"3,318",NaN,0.590,12 Jan 2001,nan,2001,TV-G
990,tt0379060,Zenon: Z3,The heroine sets out to win an important compe...,movie,TV-G,2004,11 Jun 2004,"November 12, 2019",81 min,"Adventure, Comedy, Family, Sci-Fi",...,NaN,NaN,5.5,"2,339",NaN,0.550,11 Jun 2004,nan,2004,TV-G
991,tt2948356,Zootopia,"In a city of anthropomorphic animals, a rookie...",movie,PG,2016,04 Mar 2016,"November 12, 2019",108 min,"Animation, Adventure, Comedy, Crime, Family, M...",...,Won 1 Oscar. Another 46 wins & 71 nominations.,78.0,8.0,"410,437",0.790,0.790,04 Mar 2016,0.79,2016,PG

## Filter with drop_duplicates(), and dropna()

In [26]:
df_no_missing = df.dropna()

df_no_missing.head()

df_no_missing = df.dropna(subset=["plot"])

df_no_missing.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean,rated_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999,PG-13
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018,missing
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996,G
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002,G
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",0.420,0.420,22 Nov 2000,0.42000000000000004,2000,G

In [27]:

unique_ratings = df["rated"].drop_duplicates() # string or df?

unique_ratings

unique_rating_year = df[["year_clean", "rated"]].drop_duplicates()

unique_rating_year

# very different from
unique_rating_year = df.drop_duplicates(subset=["year_clean", "rated"])
unique_rating_year

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,awards,metascore,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean,rated_clean
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,2 wins & 13 nominations.,70.0,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999,PG-13
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,NaN,NaN,6.2,124,NaN,0.620,25 Mar 2019,nan,2018,missing
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996,G
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,5 wins & 10 nominations.,NaN,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002,G
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444",0.420,0.420,22 Nov 2000,0.42000000000000004,2000,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,tt0467421,Twitches,Two teen witches who were separated at birth a...,movie,TV-PG,2005,14 Oct 2005,"November 12, 2019",86 min,"Comedy, Drama, Family, Fantasy",...,1 win.,NaN,5.7,"6,703",NaN,0.570,14 Oct 2005,nan,2005,TV-PG
958,tt0045314,Water Birds,NaN,movie,APPROVED,1952,26 Jun 1952,"May 1, 2020",30 min,"Documentary, Short, Family",...,Won 1 Oscar. Another 1 nomination.,NaN,6.9,111,NaN,0.690,26 Jun 1952,nan,1952,APPROVED
963,tt2191567,Wicked Tuna,"Teams of tuna fisherman battle the elements, a...",series,TV-14,2012–,01 Apr 2012,"February 1, 2020",60 min,Reality-TV,...,NaN,NaN,6.6,677,NaN,0.660,01 Apr 2012,nan,2012,TV-14
979,tt0247827,X-Men: Evolution,"This rendition of X-Men features Cyclops, Jean...",series,TV-Y7,2000–2003,04 Nov 2000,"November 12, 2019",23 min,"Animation, Action, Drama, Fantasy, Romance, Sc...",...,3 wins & 6 nominations.,NaN,7.9,"9,763",NaN,0.790,04 Nov 2000,nan,2000,TV-Y7
982,tt0206446,Yellowstone Cubs,"Two bear cubs, Tuffy and Tubby, are separated ...",movie,Not Rated,1963,01 Jun 1963,"November 12, 2019",48 min,Family,...,1 nomination.,NaN,6.9,177,NaN,0.690,01 Jun 1963,nan,1963,Not Rated

## Create flags based on conditions
### np.where()
### np.select()

In [28]:
# Movies from 2016+ with PG/PG-13, show selected columns
my_filter = (
    (df["type"] == "movie")
    & (df["imdb_rating"] >= 7)
    & (df["rated"].isin(["PG", "PG-13"]))
)

df_subset = df.loc[my_filter, ["title", "year", "rated", "imdb_rating"]].sort_values("imdb_rating")

In [29]:

df["quality_flag"] = np.where(df["imdb_rating"] >= 7, "good", "bad")

# conditions
conds = [
    df["imdb_rating"].ge(8.5),
    df["imdb_rating"].between(7, 8.5, inclusive="left"),
    df["imdb_rating"].between(5, 7,  inclusive="left"),
]
choices = ["top", "good", "mid"]
df["quality_group"] = np.select(conds, choices, default="bad")

df.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,...,imdb_rating,imdb_votes,avg_score_imdb_meta,avg_score_clean,release_date_clean,avg_score_char,year_clean,rated_clean,quality_flag,quality_group
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",...,7.3,"283,945",0.715,0.715,31 Mar 1999,0.715,1999,PG-13,good,good
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",...,6.2,124,NaN,0.620,25 Mar 2019,nan,2018,missing,bad,mid
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",...,5.7,"97,785",0.530,0.530,27 Nov 1996,0.53,1996,G,bad,mid
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical",...,5.8,"7,434",NaN,0.580,21 Jan 2003,nan,2002,G,bad,mid
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",...,4.9,"33,444",0.420,0.420,22 Nov 2000,0.42000000000000004,2000,G,bad,bad

## Export data

In [30]:
df_clean = df.copy(deep=True)

In [31]:
export_flag = True

if export_flag:
    df_clean.to_csv(CLEAN / "disney" / "disney_movies_clean.csv")

In [32]:
# Export by year
unique_years = df_clean["year_clean"].drop_duplicates().sort_values()
# print(unique_years)


for year in unique_years:
    # print(year)

    df_clean_year = df_clean.loc[df_clean["year_clean"] == year]
    
    # print(df_clean_year.head())
    
    out_path =  CLEAN / "disney" / "annual" / f"disney_movies_clean_{year}.csv" 
    # print(out_path)
    df_clean_year.to_csv(out_path)

    print(f"exported to: {out_path}")

exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1928.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1932.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1933.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1934.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1935.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1936.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1937.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1938.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1939.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1940.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1941.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1942.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1943.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1944.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1946.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1947.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1948.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1949.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1950.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1951.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1952.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1953.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1954.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1955.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1956.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1957.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1958.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1959.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1960.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1961.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1962.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1963.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1964.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1965.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1966.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1967.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1968.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1969.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1970.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1971.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1972.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1973.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1974.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1975.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1976.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1977.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1978.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1979.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1980.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1981.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1982.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1983.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1984.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1985.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1986.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1987.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1988.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1989.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1990.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1991.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1992.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1993.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1994.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1995.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1996.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1997.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1998.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_1999.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2000.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2001.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2002.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2003.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2004.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2005.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2006.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2007.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2008.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2009.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2010.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2011.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2012.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2013.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2014.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2015.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2016.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2017.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2018.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2019.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_2020.csv
exported to: /Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_9999.csv

In [33]:
print(out_path)

/Users/justinasgrigaitis/Documents/Github/ba-programming-2026/sessions/week_3/data/clean/disney/annual/disney_movies_clean_9999.csv